const mongoose = require("mongoose");

const Accident = mongoose.Schema({
    Accident_Number: String,
    Air_Carrier: String,
    Aircraft_Category: String,
    Aircraft_Damage: String,
    Airport_Code: String,
    Airport_Name: String,
    Amateur_Built: String,
    Broad_Phase_of_Flight: String,
    City: String,
    Country: String,
    Engine_Type: String,
    Event_Id: String,
    Factual_Report: String,
    Factual_Report_Date: Date,
    FAR_Description: String,
    Final_Report_Date: Date,
    Final_Report_HTML: String,
    Final_Report_PDF: String,
    Foreign_Report: String,
    Foreign_Report_Date: Date,
    Geolocation: {
        type: {
            type: String,
            enum: ["Point"],
        },
        coordinates: {
            type: [Number],
        },
    },
    Injury_Severity: String,
    Investigation_Type: String,
    Latitude: String,
    Longitude: String,
    Location: String,
    Make: String,
    Model: String,
    Number_of_Engines: String,
    Preliminary_Report: String,
    Preliminary_Report_Date: Date,
    Publication_Date: Date,
    Purpose_of_Flight: String,
    Registration_Number: String,
    Report_Status: String,
    Schedule: String,
    State: String,
    Total_Fatal_Injuries: String,
    Total_Serious_Injuries: String,
    Total_Minor_Injuries: String,
    Total_Uninjured: String,
    Weather_Condition: String,
});

module.exports = mongoose.model("Accident", Accident);
