const mongoose = require("mongoose");

const Incident = mongoose.Schema({
  Aircraft_Damage: String,
  Aircraft_Make: String,
  Aircraft_Model: String,
  Aircraft_Series: String,
  Aircraft_Weight_Class: String,
  Airframe_Hrs: Number,
  Airport_Name: String,
  Approach_Type: String,
  City: String,
  Data_Source: String,
  Engine_Group: String,
  Engine_Make: String,
  Engine_Model: String,
  Engine_Type: String,
  Event_Date: Date,
  Event_Remarks: String,
  Event_Type: String,
  Fatalities: Number,
  Flight_Plan_Filed: String,
  Flight_Time_Total_Hours: Number,
  Injuries: Number,
  Light_Condition: String,
  Local_Date: String,
  Mid_Air_Collision: String,
  Number_of_Engines: Number,
  Operator: String,
  Pilot_Certificates: String,
  Pilot_Qualification: String,
  Pilot_Rating: String,
  Primary_Flight_Conditions: String,
  Primary_Flight_Type: String,
  Registration_Nbr: String,
  Report_Number: String,
  Secondary_Flight_Conditions: String,
  Secondary_Flight_Type: String,
  State: String,
  Total_Aboard: Number,
  "Total_in_last_90_days_Make/Model": Number,
  Total_in_Last_90_days: Number,
  "Total_in_Make/Model": Number,
  Type_of_Operation: String,
  Visibility_Restrictions: String,
  "Visibility(mi.)": String,
  "Wind_Direction(deg)": Number,
  "Wind_Speed(mph)": Number,
});

module.exports = mongoose.model("Incident", Incident);
